exp:
    trainer: 'base'
gen:
    output: /home/jupyter/work/resources/Style-Big-GAN/logs
    gpus: 1
    kimg: 16000
    batch: 64
    loss_arch: 'base'
    loss: 'hinge'
    generator: 'res32_sngan'
    discriminator: 'res32_sngan'
    g_reg_interval: 0
    d_reg_interval: 0
    n_dis: 5
    kimg_per_tick: 32
    
data:
    dataset_path: /home/jupyter/work/resources/Style-Big-GAN/data/cifar10.zip
datasets_args:
    image_folder:
        use_labels: True
        max_size: 50000
        
gens_args:
    cnn32_dcgan:
        z_dim: 128        
        
discs_args:
    cnn32_dcgan:
        z_dim: 128
    
optim_gen_args:
    adam:
        lr: 0.0002
        betas: [0.0, 0.9]
    
optim_disc_args:
    adam:
        lr: 0.0002
        betas: [0.0, 0.9]

ema:
    use_ema: False

aug:
    aug: 'noaug'
    
    
        